import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import NextAuthSessionProviders from "./Providers/NextAuthSessionProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProviders>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </NextAuthSessionProviders>
      </body>
    </html>
  );
}
